---
- name: Linux Machine Prep
  vars_prompt:
    - name: "domain"
      prompt: "What domain will this machine join(if any)?"
  hosts: Setup
  become: yes
  tasks:
  - name: update
    ansible.builtin.package:
      name: "*"
      state: latest
  - name: install QOL packages
    ansible.builtin.package:
      name:
      - sudo
      - tldr
      - python3
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-setuptools
      - python3-setuptools
      - python3-venv
      state: latest
  - name: install AD packages
    ansible.builtin.package:
      name:
      - realmd
      - sssd
      - sssd-tools
      - libnss-sss
      - libpam-sss
      - adcli
      - samba-common-bin
      - oddjob
      - oddjob-mkhomedir
      - packagekit
      state: latest
  - name: install python packages
    pip:
      name: pexpect
  - name: prep krb5
    copy:
      dest: "/etc/krb5.conf"
      content: |
        [libdefaults]
        default_realm = {{ domain|upper }}
        rdns = false
  - name: prep mkhomedir for AD join
    copy:
      dest: "/usr/share/pam-configs/mkhomedir"
      content: |
        Name: activate mkhomedir
        Default: yes
        Priority: 900
        Session-Type: Additional
        Session:
                required                        pam_mkhomedir.so umask=0022 skel=/etc/skel
  - name: update PAM with mkhomedir
    command: pam-auth-update --enable mkhomedir
  - name: Restart
    reboot:
      reboot_timeout: 100
