---
- name: Linux Machine Prep
  vars_prompt:
    - name: "target"
      prompt: "What is this playbooks target?"
    - name: "domain"
      prompt: "What domain will this machine join(if any)?"
    - name: "user"
      prompt: "Who is the domain user to join this machine as?"
    - name: "password"
      prompt: "Domain users password"
      private: yes
  hosts: "{{ target }}"
  become: yes
  tasks:
  - name: update 
    apt:
      force_apt_get: True
      name: "*"
      state: latest
      update_cache: yes
  - name: install QOL packages 
    apt:
      force_apt_get: True
      pkg:
      - tldr
      - python
      - python3
      - python-pip
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-setuptools
      - python3-setuptools
      - python3-venv
  - name: install AD packages
    apt:
      force_apt_get: True
      pkg:
      - realmd
      - sssd
      - sssd-tools
      - libnss-sss
      - libpam-sss
      - adcli
      - samba-common-bin
      - oddjob
      - oddjob-mkhomedir
      - packagekit
  - name: install python packages
    pip:
      name: pexpect
  - name: prep mkhomedir for AD join
    copy:
      dest: "/usr/share/pam-configs/mkhomedir"
      content: |
        Name: activate mkhomedir
        Default: yes
        Priority: 900
        Session-Type: Additional
        Session:
                required                        pam_mkhomedir.so umask=0022 skel=/etc/skel
  - name: update PAM with mkhomedir
    command: pam-auth-update --enable mkhomedir
  - name: join AD
    expect:
      command: realm join "{{ domain }}" -U "{{ user }}" --os-name=`uname -o` --os-version=`uname -rsv` --install='/'
      responses:
        Password for *: "{{ password }}"
  - name: Add linux-admins to sudoers
    lineinfile:
      path: /etc/sudoers
      line: |
        #give AD admins sudo access
        %linux-admins@{{ domain }} ALL=(ALL)   ALL
  - name: Restart
    reboot: 
      reboot_timeout: 100
